### ISSUE TITLE
Fallback backend

### ISSUE THREAD

**Issue by ghost** [NCCloud/fluid#23]
It seems backend fallback in LUA is not managed correctly.
@sandromodarelli originally gave me a ping on that.

Can you give me more info please?

**Comment by sandromodarelli** [comment]
With chash balancer algorithm, the endpoint used is always the same, even if there are more than one endpoint.
The endpoint choosen is identified by "remote_addr .. ":" .. ngx.ctx.server.hostname .. ":" .. ngx.ctx.location.path"; if the endpoint fails, the next try will point again to the failing one.

**Comment by ghost** [comment]
After #26 I'll start to work on this.

**Comment by ghost** [comment]
in the next days I'll try to fix doing refactoring here #27

**Comment by ghost** [comment]
Since I were in hurry to close #27 to deploy a new version, this issue is still present and I'll try to address it on the next stage.
